-- Merge TENANT_GATEWAY into GATEWAY. Both have identical schemas.
-- GATEWAY keeps its PK (GATEWAY_ID). AIRAVATA_INTERNAL_GATEWAY_ID is added as unique column.

ALTER TABLE GATEWAY ADD COLUMN IF NOT EXISTS AIRAVATA_INTERNAL_GATEWAY_ID VARCHAR(255);

-- Backfill from TENANT_GATEWAY where possible
UPDATE GATEWAY g
  INNER JOIN TENANT_GATEWAY tg ON g.GATEWAY_ID = tg.GATEWAY_ID
  SET g.AIRAVATA_INTERNAL_GATEWAY_ID = tg.AIRAVATA_INTERNAL_GATEWAY_ID;

-- For rows without a TENANT_GATEWAY match, generate a UUID
UPDATE GATEWAY SET AIRAVATA_INTERNAL_GATEWAY_ID = UUID()
  WHERE AIRAVATA_INTERNAL_GATEWAY_ID IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_gateway_internal_id ON GATEWAY (AIRAVATA_INTERNAL_GATEWAY_ID);

DROP TABLE IF EXISTS TENANT_GATEWAY;
